### ISSUE TITLE
`inline` seems not recognized?

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#100]
Got as far as attempting to run cltorch unit tests :-)

How I run them:
- clone my `chameleon` branch, https://github.com/hughperkins/Oclgrind/tree/chameleon
  - build, install etc
- install torch-cl https://github.com/hughperkins/distro-cl , activate torch etc, ie `source ~/torch-cl/install/torch-activate`
- run:
```
oclgrind luajit -l cltorch -e 'cltorch.test()'
```

Example output:
```
|___________________________________________________________________________________________________________________  ==> inplace_abs

OCLGRIND FATAL ERROR (/home/ubuntu/git/Oclgrind/src/core/WorkItem.cpp:1595)
Undefined external function: op
When creating kernel 'THClTensor_pointwiseApplyD'
kernel build error:

kernel source:
1: // OpenCL kernels....
2: 
3: // expected templated values:
4: // dims (vector of unique dimension values)
5: // operation
6: // dim1
7: // dim2
8: // dim3
9: // ... dimD
10: // num_input_tensors
11: // include_scalar_input
12: //
13: // maybe should add:
14: // IndexType (hardcoded to int for now)
15: // MAX_CUTORCH_DIMS (hardcoded to 25 for now)
16: 
17: // (Ported from cutorch's THCApply.cuh)
18: 
19: // Maximum number of dimensions allowed for cutorch
20: // #define MAX_CUTORCH_DIMS 25
21: 
22: // Enum that indicates whether tensor arguments are read/write or
23: // read-only
24: //enum TensorArgType { ReadWrite, ReadOnly };
25: 
26: 
27: 
28: inline void op( global float *out
29:   
30:   
31:    
32: ) {
33:     *out =fabs( *out );
34: }
35: 
36: kernel void
37: THClTensor_pointwiseApplyD(
38:    
39:     int offset_1,
40:     
41:     
42:     global float*data_1,
43:    
44:    
45:    
46:    int totalElements) {
47:    int linearIndex = get_global_id(0);
48:    if(linearIndex < totalElements ) {
49:     
50:     
51:       
52:       
53:          int derived_offset_1 = linearIndex + offset_1;
54:       
55:     
56: 
57:     op(
58:       
59:          
60:          &(data_1[derived_offset_1])
61:       
62: 
63:       
64: 
65:        
66:     );
67:   }
68: }
69: 
70: 


```

**Comment by hughperkins** [comment]
probably you could just ignore the `inline` keyword?  Seems like the goal of oclgrind is not performance, and performance is the only advantage of `inline` really, mostly?

**Comment by jrprice** [comment]
This is a fun one, since this is technically a bug with your code, not Oclgrind. See more in the "Inline functions" section on the [troubleshooting page](https://github.com/jrprice/Oclgrind/wiki/Troubleshooting).

As noted there, the quick fix should just be to throw `static` in front of `inline`.

**Comment by hughperkins** [comment]
Ah, the problem with that is, if I remember correclty, I get build warnings on AMD... I think ... but ... ok... seems like `static inline` is correct.  Will give that a shot.

**Comment by jrprice** [comment]
For reference, Oclgrind just uses Clang to compile OpenCL kernels, so I'm not in a position to easily 'ignore' the `inline` keyword.

**Comment by hughperkins** [comment]
Ok.  Fair enough :-)  Trying `static inline` :-)

**Comment by hughperkins** [comment]
well, that works :-)  at least on oclgrind

**Comment by hughperkins** [comment]
Interestingly, having made this one change, almost all other tests pass ok:
```
Completed 227 asserts in 116 tests with 4 errors
```

**Comment by hughperkins** [comment]
Example showing that `static inline` doesnt work on AMD cards: https://github.com/jcjohnson/neural-style/issues/246

**Comment by hughperkins** [comment]
Oh wait, actually, seems those are jus twarnings in fact.  the error is somewhere else.  The warnings are not very nice looking though....
