### ISSUE TITLE
When in 'interactive' how to get workgroupsize, number workgroups, local memory size, private memory size?

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#101]
When in 'interactive' how to get workgroupsize, number workgroups, local memory size, private memory size?

**Comment by hughperkins** [comment]
(maybe one way to do this would be to be ble to do things like:
```
p get_num_groups(0)
``` ... etc ?

**Comment by jrprice** [comment]
The `info` command will give you some of this information:

    (oclgrind) info
    Running kernel 'nbody'
    -> Global work size:   (4096,1,1)
    -> Global work offset: (0,0,0)
    -> Local work size:    (1,1,1)

**Comment by hughperkins** [comment]
cool.  Thanks!
