### ISSUE TITLE
`n` in interactive seems to step into, rather than step over?

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#102]
In interactive mode, doing `n` to step-over a function call seems to result in it in fact stepping into the function?

Also seems to be misisng a 'step out' command?

**Comment by jrprice** [comment]
I can't seem to reproduce this locally - `n` is stepping over function calls just fine for me. Do you have a simple kernel that reproduces this?

I agree, a `step out` would be a useful addition.

**Comment by hughperkins** [comment]
trying to step over https://github.com/hughperkins/cltorch/blob/add-sort/src/lib/THClSortUtils.cl#L118 fails.  it steps into https://github.com/hughperkins/cltorch/blob/add-sort/src/lib/THClReduceApplyUtils.cl#L61  Maybe becuase it is `static inline` I suppose is not an unreasonable reason?

**Comment by hughperkins** [comment]
Hmmm, I cant reproduce at the moment.

=> closed
