### ISSUE TITLE
Strange warning about unitialized value?

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#105]
Following code:
```
(oclgrind) l 208
203	      keys_data[keyStartOffset + elem2 * keySliceStride] : (float) 0;
204	    float v2 = valid2 ?
205	      values_data[valueStartOffset + elem2 * valueSliceStride] : (float) 0;
206	
207	    p_sharedKeys[elem2] = k2;
208	    p_sharedValues[elem2] = v2;
209	    p_sharedValid[elem2] = valid2;
210	
211	    barrier(CLK_LOCAL_MEM_FENCE);
212	
```

Following warning about unitialized value:
```
Uninitialized value written to local memory address 0x20000000000d0
	Kernel: bitonicSortKVInPlace
	Entity: Global(20,0,0) Local(20,0,0) Group(0,0,0)
	  store float %44, float addrspace(3)* %47, align 4, !dbg !115
	At line 208 of input.cl:
	  p_sharedValues[elem2] = v2;
```
v2 is a float.  Its initialized at line 204.  It seems kind of challenging to pass line 204 without initializing its value.  Thoughts?

**Comment by jrprice** [comment]
The uninitialised memory plugin is currently missing origin tracking, so it is likely that the uninitialised value is propagating from earlier on. For example, if the data at `values_data[valueStartOffset + elem2 * valueSliceStride]` (used in the assignment to `v2`) is not properly initialised, this could cause this error.

**Comment by hughperkins** [comment]
Yes, seems plausible.  Where/how does it start tracking 'uninitialized'?  `values_data` is a passed-in buffer, of unknown state.  Or is it tracking changes across kernel launches?

**Comment by hughperkins** [comment]
Maybe I will try to provide some simple example, rather than my templatized have-to-install-entire-cltorch stuff :-P  You can close until I provide such an example if you want.  (same for my segfault, and the 'n, step out' issue).

**Comment by jrprice** [comment]
It tracks across kernel launches. If `values_data` is initialised by the host (`clEnqueueWriteBuffer`, `clEnqueueMapBuffer` etc) or by a previous kernel, then you *shouldn't* see this error message.

**Comment by hughperkins** [comment]
ah. interesting.  thats new information :-)  anyway, please feel free to close this for now, until I provide a suitable example.  In fact, I'll close it now:

**Comment by hughperkins** [comment]
Kind of weird.  I've reproduced my code in pyopencl, but cannot reproduce the uninitialized value error.  Kind of odd...  One thing I noticed is that in the torch code, if I add a `clFinish()` between the 1st and 2nd kernel, then the warnings go away.  Which is strange, since they're in an in-order queue (as far as I know.  unless they're somehow not???).

**Comment by hughperkins** [comment]
random question: is there some possible scenario where oclgrind would consider the queue to be out-of-order, without having been explicitly asked to as such?

**Comment by hughperkins** [comment]
(note that I'm creating the queue in torch like: ```
    *queue = clCreateCommandQueue(*context, device, 0, &error);
``` ... which should create an in-order queue, right?)

**Comment by hughperkins** [comment]
(seems like you dont accept out-of-order queues anyway, and therefore assume in-order, so seems this is not the reason
```
CL_API_ENTRY cl_command_queue CL_API_CALL
clCreateCommandQueue
(
  cl_context                   context,
  cl_device_id                 device,
  cl_command_queue_properties  properties,
  cl_int *                     errcode_ret
) CL_API_SUFFIX__VERSION_1_0
{
  // Check parameters
  if (!context)
  {
    SetErrorArg(NULL, CL_INVALID_CONTEXT, context);
    return NULL;
  }
  if (device != m_device)
  {
    SetErrorArg(context, CL_INVALID_DEVICE, device);
    return NULL;
  }
  if (properties & CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE)
  {
    SetErrorInfo(context, CL_INVALID_QUEUE_PROPERTIES,
                 "Out-of-order command queues not supported");
    return NULL;
  }

  // Create command-queue object
  cl_command_queue queue;
  queue = new _cl_command_queue;
  queue->queue = new oclgrind::Queue(context->context);
  queue->dispatch = m_dispatchTable;
  queue->properties = properties;
  queue->context = context;
  queue->refCount = 1;

  clRetainContext(context);

  SetError(context, CL_SUCCESS);
  return queue;
}
```
)

**Comment by hughperkins** [comment]
I think for the uninitialized values, it might be easier to use if it is launch-specific: ie, if you attempt to read local memory that you didnt write to yet.  But I'm not sure that reading from global memory that a previous kernel didnt write to should be in the basic form of this check? At least: maybe this should be configurable/optional?
