### ISSUE TITLE
Looking at Oclgrind internals [ML] ?

### ISSUE THREAD

**Issue by UniqueFool** [jrprice/Oclgrind#109]
There are machine-learning frameworks that help people to tune/optimize OpenCL kernels, e.g. see https://github.com/CNugteren/CLTune

For some background info, see: http://www.cedricnugteren.nl/downloads/handouts2016a.pdf

And specifically: http://arxiv.org/pdf/1506.00842v1.pdf

The question is whether oclgrind could be used to gather additional kernel specific information by looking at runtime information for a kernel, e.g. the dataflow between invocations for different data sets and use that for machine-learning purposes.

Specifically, this would look at the type/size of a variable and monitor its lifetime/scope and the way it is mutated - to do that, one would need a way to "capture" oclgrind state and serialize that, so that it can be used for ML.

The ML algorithm could then have much more, and much better, information for tuning a kernel, because it would know more about the runtime behavior of the kernel.

**Comment by jrprice** [comment]
I complete agree. I've considered this sort of thing in the past myself but have not yet had the time to try any of this out.

**Comment by UniqueFool** [comment]
As long as Oclgrind could provide some kind of interface to get kernel-specific information, we could get in touch with a project like CLTune and try to hook this information up to the ML pipeline.

**Comment by jrprice** [comment]
Closing this - while it's certainly an interesting discussion there isn't any specific issue to address here. I *think* Oclgrind already provides hooks for most of the interesting information you'd want to get for this sort of thing, and if anything else specific is missing that can be requested in a separate issue.
