### ISSUE TITLE
OCLGRIND device somehow bypassed by OpenCV

### ISSUE THREAD

**Issue by gkontsevich** [jrprice/Oclgrind#114]
Hi again,

I've hit an interesting problem while trying to debug the OpenCV HOG module. Their OpenCL kernel doesn't seem to be working correctly in our use-case and I'm trying to use OCLGRIND to narrow down the issue.

However I've run into a problem where it seems OpenCV somehow manages to ignore the OCLGRIND virtual device and runs on the actual GPU (in my case the integrated graphics)

At first I thought this is a peculiarity of my program, however I've run the brain dead simple example provided by OpenCV and based on the performance it seems to be running on the GPU

Specifically I'm running:

`oclgrind -i gdb tapi-example-hog`

The example is in opencv under /opencv-3.0.0/bin/tapi-example-hog
(the example has a bit of a quirk in that you need to have it run in grey scale for the OpenCL code to be called)

It shows about 2 FPS in CPU-Mode and about 15 FPS in OpenCL-Mode as you'd expect when running on the GPU, not OCLGRIND. I've stepped through the code with GDB and confirmed that the kernel is indeed getting launched and is returning with a successful error code.

The oclgrind interactive debugger however doesn't seem to get triggered and as far as I can tell is receiving nothing. (OCLGRIND unfortunately gives very very sparse feedback, so sometimes you doubt it's even running)

To sanity check I ran the same command on a simple matrix vector multiplication (which you helped me fix in a preview posted issue - thank you again) and it behaves as you'd expect: first running GDB and then dropping down to OCLGRIND's interactive debugger when the kernel is launched

`oclgrind -i gdb matvec`

I was wondering if this is an issue with OCLGRIND and if there is anything I can do to force OpenCV to run on the virtual device.

Thank you for the wonderful tool, 
and thank you for your help as always.

George

**Comment by jrprice** [comment]
I've had issues when trying to run an application through both Oclgrind and a host debugger (like GDB) at the same time. Have you tried just with Oclgrind and no GDB (e.g. `oclgrind -i tapi-example-hog)?

It's also possible that OpenCV handles OpenCL in a slightly strange way. For example, if it explicitly uses `dlopen()` on `libOpenCL.so`and extracts function pointers manually instead of actually linking against an OpenCL library at build time, then Oclgrind's `LD_PRELOAD` mechanism won't work.

I'll try and take a look at Oclgrind+OpenCV when I get a chance, maybe there's a workaround.

**Comment by jrprice** [comment]
> For example, if it explicitly uses dlopen() on libOpenCL.soand extracts function pointers manually instead of actually linking against an OpenCL library at build time, then Oclgrind's LD_PRELOAD mechanism won't work.

Yep, [that's what it does](https://github.com/opencv/opencv/blob/master/modules/core/src/ocl.cpp#L770).

Let me have a think about this, OpenCV has a big enough user base to make it desirable to fix this.

**Comment by gkontsevich** [comment]
Thank you so much for looking into this. I really appreciate it

**Comment by jrprice** [comment]
Should be fixed now by [this commit](https://github.com/jrprice/Oclgrind/commit/34fb14f6945cd50b7e82ba0c8ca4fce8622c39c9).
