### ISSUE TITLE
Overflow in rhadd result

### ISSUE THREAD

**Issue by mpflanzer** [jrprice/Oclgrind#116]
In Oclgind the intermediate result of the `rhadd` built-in function seems to overflow.
For example `rhadd(0UL, 0xFFFFFFFFFFFFFFFFUL)` computes `0x0` whereas it should be `0x8000000000000000`.

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/hadd.html

**Comment by mpflanzer** [comment]
The problem is that `b+1` overflows in this case during the carry checking:
```
uint64_t c = (a > UINT64_MAX-(b+1)) ? (((uint64_t)1)<<63) : 0;
```

What is the reason for not using the same logic as in the signed case? Currently I can't think of a case where
```
            int64_t c = (a | b) & 1;
            result.setSInt((a>>1) + (b>>1) + c, i);
```
would not work. (Of course uint64_t and setUInt would have to be used.)

`hadd` should work correctly as there is no additional `+1` but if you change `rhadd` to use the same logic for both signed and unsigned you might want to change `hadd` as well.

**Comment by jrprice** [comment]
You're right. I have no idea why I wrote the `uint64_t` variants like that. I've just pushed a fix for this (with a test case).

Thanks for reporting!
