### ISSUE TITLE
calling clCompileProgram with source that has #include statements fails

### ISSUE THREAD

**Issue by georgevanvenrooij** [jrprice/Oclgrind#133]
When attempting to compile a .cl source that contains #include statements I get an error. The general approach is this:

For each header file, I create a program by calling clCreateProgramWithSource() and build 2 arrays, one with the header filenames and another with the corresponding programs.
For the source file, I create a program by calling clCreateProgramWithSource() and then call clCompileProgram() on the source program with the header names and programs passed to it. This call then generates an OCLGrind runtime error.

**Comment by jrprice** [comment]
Can you provide the full error that you receive, and maybe show some of the code that creates and builds the programs? There are test cases that cover this stuff in my nightly tests and they all pass, so I'm going to need some more information to narrow this down.

**Comment by georgevanvenrooij** [comment]
I'm using Boost.Compute functionality for the code that creates & builds the programs so it's a bit hard to give you the code that does this, I will have a look this week to see if I can make a smaller example that I can post.

**Comment by jrprice** [comment]
Closing stale bug - please reopen if you can provide a reproducer.
