### ISSUE TITLE
Undefined external for function from header with inline keyword

### ISSUE THREAD

**Issue by avgurt9** [jrprice/Oclgrind#142]
//vecadd_cl.h
#ifndef VECADD_CL_H
#define VECADD_CL_H

inline int addI(int a,int b){
    return a+b;
}

#endif // VECADD_CL_H

//vecadd.cl
__kernel void vectorAdd(int n,__global const int *a,__global const int *b,__global int *c){
    const int i=get_global_id(0);
    if(i>=n){
        return;
    }
    c[i]=addI(a[i],b[i]);
}

OCLGRIND FATAL ERROR (/build/oclgrind-nvLNg6/oclgrind-16.10/src/core/WorkItem.cpp:1591)
Undefined external function: addI
When creating kernel 'vectorAdd'

works fine without 'inline' keyword

**Comment by jrprice** [comment]
This should be fixed as of a82dc87, and therefore the next release. In the meantime, you can fix this in your own code by using `static inline` instead, or by passing `-fgnu89-inline` to `clBuildProgram`.

FWIW, using `inline` in the way that you are using it is not strictly valid C99/OpenCL code, so you may find other OpenCL platforms sometimes fail to compile code like this too (e.g. [AMD's ROCm](https://github.com/RadeonOpenCompute/ROCm/issues/77)).

**Comment by jrprice** [comment]
Oclgrind 18.3 has now been released:
https://github.com/jrprice/Oclgrind/releases
