### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Athas** [jrprice/Oclgrind#146]
I'm trying to package oclgrind for Fedora (I hope that's okay), but I'm running into the issue that the latest release (16.10) will not build with the most recent versions of LLVM (due to LLVM splitting ReaderWriter.h into two header files, incorporated by oclgrind in 989ee27653b1a62d7b30f0bdd03e9b9d59f8f919, a few months after 16.10 was released).  Could a new release of oclgrind be considered?

**Comment by jrprice** [comment]
That's great!

Yes, a new release with support for LLVM 4.0/5.0/6.0 is currently planned for early 2018, probably January or early February.

**Comment by Athas** [comment]
Good to hear.  I'll wait until then.

**Comment by Athas** [comment]
Any news on a release?  I would also like to add oclgrind to Homebrew, but they only provide LLVM 5.0.1.

**Comment by jrprice** [comment]
Apologies for the delay - I've just been holding off for the LLVM 6.0 release to ensure compatibility and to use it for the building the release binaries. Looking at the LLVM mailing list it seems like the next RC should be by the end of the week, so potentially expecting the final 6.0 tag next week.

**Comment by jrprice** [comment]
Oclgrind 18.3 has been released, with support for LLVM versions 3.9 through to 6.0:
https://github.com/jrprice/Oclgrind/releases
