### ISSUE TITLE
Oclgrind creates link that hides OpenCL installation

### ISSUE THREAD

**Issue by RichardSchulze** [jrprice/Oclgrind#156]
Thank you for developing Oclgrind. It has helped me a lot in finding bugs in my OpenCL kernels!

I installed Oclgrind on Ubuntu 16.04 using APT. The installation created a link under `/usr/local/lib/libOpenCL.so` that points to `liboclgrind.so` in the same directory. That causes all my OpenCL applications to only find the Oclgrind platform, even if I don't start them with the `oclgrind` command. When I delete the link, everything works fine, but unfortunately the link keeps reappearing periodically.

Do you know why the link keeps reappearing and is this done intentionally? How can this be fixed?
Many thanks in advance!

**Comment by jrprice** [comment]
This sounds really weird. The Oclgrind Debian package (from which the Ubuntu package is derived) does not create any `libOpenCL.so` symlinks.

I'm also confused as to why you are seeing `liboclgrind.so` in `/usr/local/lib`. I'd expect the package to install everything to `/usr/lib` (this is what it does for me, although I'm on 18.04). Do you have any non-standard APT settings that might be interfering with this stuff?

**Comment by RichardSchulze** [comment]
Thank you for your answer.

> Do you have any non-standard APT settings that might be interfering with this stuff?

I don't think so. It is a clean Ubuntu 16.04 with the Intel OpenCL SDK and Oclgrind installed.

**Comment by jrprice** [comment]
I've just created a VM with a clean installation of Ubuntu 16.04. I've run `apt-get install oclgrind`, and it hasn't created anything in `/usr/local/lib`:

```
james@ubuntu-16:~$ dpkg-query -L oclgrind
/.
/usr
/usr/bin
/usr/bin/oclgrind
/usr/bin/oclgrind-kernel
/usr/lib
/usr/lib/oclgrind
/usr/lib/oclgrind/liboclgrind-rt.so
/usr/share
/usr/share/doc
/usr/share/doc/oclgrind
/usr/share/doc/oclgrind/NEWS.gz
/usr/share/doc/oclgrind/copyright
/usr/share/doc/oclgrind/README.gz
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/oclgrind.1.gz
/usr/share/man/man1/oclgrind-kernel.1.gz
/usr/share/doc/oclgrind/changelog.Debian.gz

james@ubuntu-16:~$ dpkg-query -L liboclgrind-15.5 
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/oclgrind
/usr/lib/x86_64-linux-gnu/oclgrind/15.5
/usr/lib/x86_64-linux-gnu/oclgrind/15.5/clc64.pch
/usr/lib/x86_64-linux-gnu/oclgrind/15.5/clc.h
/usr/lib/x86_64-linux-gnu/oclgrind/15.5/clc32.pch
/usr/lib/x86_64-linux-gnu/liboclgrind-15.5.so
/usr/share
/usr/share/doc
/usr/share/doc/liboclgrind-15.5
/usr/share/doc/liboclgrind-15.5/copyright
/usr/share/doc/liboclgrind-15.5/changelog.Debian.gz
```

Reading around a bit it sounds like APT should never install things to `/usr/local` - this directory is reserved for software compiled and installed manually.

**Comment by RichardSchulze** [comment]
Thank you for testing the issue. It seems like this might then be specific to my system.
