### ISSUE TITLE
Error: CL_OUT_OF_RESOURCES: total local memory exceeds device maximum

### ISSUE THREAD

**Issue by L30nardoSV** [jrprice/Oclgrind#162]
My application has four kernels, each one consuming around 10000 bytes of local memory, and only one kernel runs at a time. The application runs fine on both Nvidia and AMD GPUs

However, oclgrind shows the following error:

```
Oclgrind - OpenCL runtime error detected
	Function: clEnqueueNDRangeKernel
	Error:    CL_OUT_OF_RESOURCES
	total local memory size (41492) exceeds device maximum of 32768

Error: clEnqueueNDRangeKernel() -5
```

The local memory reported by oclgrind (41492) seems to roughly match that of all four kernels combined.
I would expect something around 10000 for any kernel. 

Also I used CodeXL (analysis mode) and checked that LDS usage for that kernel is 10408 bytes, i.e., < 
 the maximum 32768.

Any ideas why the error message in this case?

**Comment by jrprice** [comment]
Ah, I think I see the bug. The local memory arrays are pulled out into global variables by Clang/LLVM, and Oclgrind assumes they're all used by any kernel that is in the same source file.

I'll try and get this fixed shortly.

**Comment by L30nardoSV** [comment]
Many thanks for the clarification!

**Comment by jrprice** [comment]
Fixed - thanks for the bug report!
