### ISSUE TITLE
Running Oclgrind on Windows 10 issue

### ISSUE THREAD

**Issue by micham1111** [jrprice/Oclgrind#180]
I've installed Oclgrind-19.10-Windows.zip and Visual Studio 2019.
(clang is not installed on my computer).
I use the program provided at https://github.com/jrprice/Oclgrind/tree/master/tests/apps/vecadd
and I get the following error:
	1 error generated.
	fatal error : malformed or corrupted AST file : 'could not find file 'C : \Program Files\LLVM\lib\clang\9.0.1\include\opencl - c - base.h' referenced by AST file 'C:\Program Files\Oclgrind\x64\lib / .. / include / oclgrind//opencl-c-1.2-64.pch''
	Error during operation 'building program': -11
Does any one know how to solve this issue?
Any suggestions are appreciated.
Please Advice,

Best regards,
Micha

**Comment by jrprice** [comment]
It's possible I did something wrong when building the binaries, or something about Clang's handling of precompiled headers has changed. Can you try the [18.3 release](https://github.com/jrprice/Oclgrind/releases/tag/v18.3) to see if that works for you?

**Comment by micham1111** [comment]
Thanks.
version 18.3 work fine.
Thanks,
Micha

**Comment by isuruf** [comment]
Newer versions of `opencl-c.h` is not one file and has a include directive to `opencl-c-base.h` and Oclgrind's generating of stringified `opencl-c.h` is inadequate. https://github.com/jrprice/Oclgrind/blob/master/CMakeLists.txt#L162

**Comment by Juanlu001** [comment]
This error appeared with `oclgrind_binary_distribution-18.3.post1-py2.py3-none-manylinux1_x86_64.whl`. However, installing the 18.3 was recommended as a workaround, so I'm not following. What can users do while this problem is being worked on? Thanks a lot!

**Comment by Juanlu001** [comment]
(Just in case: the "fatal error: malformed or corrupted AST file" message appears both with `18.3.post1` and `18.3`)

**Comment by isuruf** [comment]
>What can users do while this problem is being worked on? 

@Juanlu001, download `opencl-c-base.h` from clang 6.0.0 and place it at the directory that Oclgrind tells you that it is missing from.

**Comment by isuruf** [comment]
@Juanlu001, are you sure you are getting the same error message? Those wheels were built with LLVM 6.0.0 or 7.0.1 which doesn't have this problem.

**Comment by Juanlu001** [comment]
@isuruf This is the error @FlorianPignol and I are observing:

```
...
  File "/home/florian/.pyenv/versions/diq35/lib/python3.5/site-packages/pyopencl/__init__.py", line 510, in build
    options_bytes=options_bytes, source=self._source)
  File "/home/florian/.pyenv/versions/diq35/lib/python3.5/site-packages/pyopencl/__init__.py", line 554, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILUREBuild on <pyopencl.Device 'Oclgrind Simulator' on 'Oclgrind' at 0x560ee2d30430>:fatal error: malformed or corrupted AST file: 'could not find file '/home/florian/.pyenv/versions/diq35/lib/python3.5/site-packages/pyopencl/.libs/../../oclgrind_binary_distribution/.libs/../../oclgrind_binary_distribution/.libs/include/opencl-c.h' referenced by AST file '/home/florian/.pyenv/versions/diq35/lib/python3.5/site-packages/pyopencl/.libs/../../oclgrind_binary_distribution/.libs/../../oclgrind_binary_distribution/.libs/include//opencl-c-1.2-64.pch''(options: -I /home/florian/.pyenv/versions/3.5.9/envs/diq35/lib/python3.5/site-packages/pyopencl/cl -D PYOPENCL_USING_OCLGRIND)
(source saved as /tmp/tmpeuxoh2pp.cl)
```

Sorry I can't share code to reproduce at the moment, we're still debugging.

**Comment by isuruf** [comment]
That's unrelated to this issue. Please open an issue in https://github.com/isuruf/ocl-wheels

**Comment by Juanlu001** [comment]
Thanks @isuruf, sorry for the noise - will do tomorrow.

**Comment by isuruf** [comment]
#184 didn't fix this completely. https://github.com/jrprice/Oclgrind/pull/197 does.
