### ISSUE TITLE
Segmentation fault when running oclgrind

### ISSUE THREAD

**Issue by vidlefak** [jrprice/Oclgrind#182]
Hi,

I've installed oclgrind on my ubuntu computer and that's the error I get:
> user@cuda3:/tmp/project/verify_first_copy$ oclgrind ./tests
/usr/bin/oclgrind: line 145: 25743 Segmentation fault      (core dumped) LD_LIB                                RARY_PATH=$LIBDIR:$LD_LIBRARY_PATH LD_PRELOAD=$LIBDIR/liboclgrind-rt.so "$@"

Do you know maybe what can be the reason of that ? Is it possible I did something wrong in the installation ?

**Comment by ilaychen** [comment]
Wow this is exactly my problem as well.
Anyone can help?

**Comment by jrprice** [comment]
Apologies for the slow reply. I have a couple of questions so that I can try and reproduce the error:

1. Which version of Ubuntu are you running?

2. Did you compile Oclgrind yourself, or install it from the Ubuntu repositories via `apt`?

**Comment by vidlefak** [comment]
Thanks.
My ubuntu version is 16.04.6 LTS (xenial) and I've installed Oclgrind via apt.

**Comment by jrprice** [comment]
Resolved offline.
