### ISSUE TITLE
Question about optimisation flags

### ISSUE THREAD

**Issue by mn416** [jrprice/Oclgrind#189]
First off, thanks for a great tool!

It appears that Oclgrind does not ask the compiler to perform much optimisation (my system has LLVM/Clang version 6.0 installed).  By default, the following kernel compiles to 40 instructions (approx, measured using `--dump-spir`) but only 16 instructions (approx) when I change `-O0` to `-O` on [line 288 of Program.cpp](https://github.com/jrprice/Oclgrind/blob/master/src/core/Program.cpp#L288).

```
__kernel void vecAdd(__global const float* a, __global const float* b, __global float* c, int n)
{
    int id = get_global_id(0);
    if (id >= n) return;    
    c[id] = a[id] + b[id];
}
```

I wonder, is this expected?  In other words, does Oclgrind do fairly minimal optimisation by default?  Is there an important reason for passing `-O0` rather than `-O` to the compiler?  The comment in `Program.cpp` says that Oclgrind performs optimisation passes manually, but it's not clear to me that this is actually happening.

Background: I've modified Oclgrind to count loads/stores of pointers separately from non-pointers (which appears to work fine).  But I was surprised to see lots of pointer loads/stores when running kernels where I would expect none (as if private pointer variables are being fetched from the stack every time round a loop).  This is due to the problem described above (if I use `-O` all the pointer loads/stores disappear for the above example).

I'm happy to provide further details.

**Comment by jrprice** [comment]
Sorry for the slow reply here. I've taken a quick look at this and reproduced the behaviour. By default, Oclgrind **does** run a standard set of compiler optimisations (corresponding to -Oz, see [here](https://github.com/jrprice/Oclgrind/blob/master/src/core/Program.cpp#L505)), but for some reason these no longer seem to be making much difference. I'm sure they used to, so maybe something has changed as part of LLVM's switch to a newer pass manager.

I'll try and take a detailed look into why this isn't working soon, but in the meantime forcing optimisations by manually adding a `-O<something>` flag seems reasonable. I'm sure there was a good reason that I made Oclgrind disable optimisations and manually add the passes later on, but I can't remember what it is right now.

**Comment by jrprice** [comment]
I did some archeology and remembered that I used to disable optimisations and manually apply them later because there used to be some problematic LLVM passes that broke things. As far as I can tell this is no longer I problem, so I've changed things to let Clang apply `-Oz` by default.
