### ISSUE TITLE
Unable to treat llvm 'freeze' instruction.

### ISSUE THREAD

**Issue by huypn12** [jrprice/Oclgrind#194]
LLVM 10 added new instruction 'freeze' and currently OclGrind does not have the necessary logic to process it. 

![image](https://user-images.githubusercontent.com/2792821/102112563-2aacf200-3e38-11eb-8fb8-d6248b66733c.png)

**Comment by huypn12** [comment]
![image](https://user-images.githubusercontent.com/2792821/102113117-ee2dc600-3e38-11eb-9001-d32a9e485d6c.png)

**Comment by huypn12** [comment]
￼￼￼How do you think about replacing freeze by a NOP-alike logic like this?

![image](https://user-images.githubusercontent.com/2792821/102115901-79f52180-3e3c-11eb-81d3-e6af36cc7078.png)

**Comment by jrprice** [comment]
I think a NOP approach like that is good, but I this exact code might not work for `struct` operands. I'd suggest just doing a direct `memcpy` on the data, the same as how the `bitcast` instruction is implemented. Feel free to open a PR for this, or I can try and get to it later this week.

**Comment by huypn12** [comment]
Thanks, PR submitted.
