### ISSUE TITLE
Add support for half precision floating point

### ISSUE THREAD

**Issue by jrprice** [jrprice/Oclgrind#39]

**Comment by athas** [comment]
What is the qualification on "mostly"?  I have an OpenCL program that uses the `half` type (and the `cl_khr_fp16` extension) and it fails with "Unsupported constant type: 1".  I can see a way to get started on adding support myself (by handling `llvm:Type::HalfTyId`), but maybe I'm on the wrong track.

**Comment by jrprice** [comment]
This was a while ago, but I suspect that I just implemented the parts of FP16 required by the core spec, so it doesn't include the `cl_khr_fp16` extension. It might not be too much work to implement most/all of `cl_khr_fp16` though, and handling `llvm:Type::HalfTyId` is definitely the right place to start.
