### ISSUE TITLE
vecadd fails to verify on x86 Linux

### ISSUE THREAD

**Issue by silverclaw** [jrprice/Oclgrind#66]
make check fails to verify vecadd. This is caused by compiler optimisations rather than a failure of oclgrind itself.
The test vecadd has to be compiled with "-ffloat-store". I do not understand ./configure and autotools well enough to do it myself, but I've configured with CFLAGS="-ffloat-store" and verified that setting the above flag makes the test pass.
This may be dependent on my own version of gcc: Gentoo 4.8.3 p1.1, pie-0.5.9

**Comment by jrprice** [comment]
Interesting. How significant is the difference between Oclgrind and the reference values? Assuming it's fairly small, an alternative solution would be to increase the tolerance for the verification slightly (`#define TOL` near top of `vecadd.c`). It's currently set to `1e-8`, which is just an arbitrary value that seemed to work on my machines.

**Comment by silverclaw** [comment]
I've hacked the test to print the differences:

Difference: 0x3E60000000000000
Difference: 0x3E70000000000000
Difference: 0x3E60000000000000
Difference: 0x3E60000000000000
Difference: 0x3E60000000000000
Difference: 0x3E70000000000000
Difference: 0x3E70000000000000

(this is for a few of the tests)
For completeness, the hex for TOL is 0x3E45798EE2308C3A

I am not sure how relevant the tolerance constant is, but adjusting it seems to be doing a work-around to cause the test to artificially accept values. Ideally, the "reference" value should be computed within the same precision as the device being tested.

**Comment by silverclaw** [comment]
Specifying -std=c99 instead of -std=gnu99 also fixes this. I did it by changing the configure script accordingly.
I can submit that on my own branch and then submit a pull request if you prefer.

**Comment by jrprice** [comment]
Ah, I like that fix. We already use `-std=c99` in the CMake build, and I hadn't realised that autoconf was picking `-std=gnu99` instead of `-std=c99`. If you have a patch ready to go that would be great!

**Comment by silverclaw** [comment]
Actually, no I don't know how to do it. I forgot that my configure script is generated through autoconf -i.
Can't we just use CMake all around and ditch autoconf ?

**Comment by jrprice** [comment]
Heh, feel free to use CMake instead! I'll fix the autoconf script. I've been thinking about moving to solely to CMake, but I seem to know too many people that prefer the `configure / make / make install` workflow.

**Comment by jrprice** [comment]
Should be fixed in bfd18f6.
