### ISSUE TITLE
Include of CL/cl.h in tests/common/common.h breaks on Mac

### ISSUE THREAD

**Issue by mpflanzer** [jrprice/Oclgrind#70]
Since Apple has different name for its OpenCL include path the include in tests/common/common.h does not work on Mac. Did you intended to include the file src/CL/cl.h?

**Comment by jrprice** [comment]
Yes, I forgot to add `src/` to the include path for the tests when I updated the Makefile structure. Should be fixed in 420b301, please verify and close if it is.

**Comment by mpflanzer** [comment]
Yes, works now. Thanks.
