### ISSUE TITLE
printing private variable of type unsigned char causes segmentation fault

### ISSUE THREAD

**Issue by JohnReppy** [jrprice/Oclgrind#73]
(oclgrind) p sts
/usr/local/oclgrind/bin/oclgrind: line 150: 17334 Segmentation fault: 11  DYLD_LIBRARY_PATH=$LIBDIR:$DYLD_LIBRARY_PATH DYLD_INSERT_LIBRARIES=$LIBDIR/liboclgrind-rt.dylib DYLD_FORCE_FLAT_NAMESPACE=1 "$@"

Running on Mac OS X 10.10.4.  I suspect that the problem has to do with the type of sts, which is uchar *(it is a private variable).  I'm using oclgrind v15.5.2.

**Comment by jrprice** [comment]
This should be fixed by 36a34f7.

As a workaround (until the next binary release), this *should* work if you tell Oclgrind not to apply any optimizations to the kernels that it builds, like this:

    oclgrind --build-options "-O0" ...
