### ISSUE TITLE
Any support for int64 atomics planned?

### ISSUE THREAD

**Issue by rmcgibbo** [jrprice/Oclgrind#78]
Hi, this is a really neat project. From looking at CL_DEVICE_EXTENSIONS, I see that the 32 bit int atomic extensions are supported. Are there any plans to support the 64 bit atomics as well (cl_khr_int64_base_atomics)?

**Comment by jrprice** [comment]
This shouldn't be too difficult, I'll try and get round to this soon.

**Comment by petrkalos** [comment]
@jrprice Have you already start implementing this? If not I can send you over my implementation for review (I only have atom_add/inc but it won't take too long to implement the rest).

**Comment by jrprice** [comment]
@petrkalos I still haven't got round to this yet. If you're working on it, then that would be much appreciated.

**Comment by petrkalos** [comment]
I'll prepare a merge request.
