### ISSUE TITLE
Removing autotools build system

### ISSUE THREAD

**Issue by jrprice** [jrprice/Oclgrind#83]
I'm opening this issue mostly to notify anyone that is working with Oclgrind that I intend to remove the autotools based build system, at some point in the (not too distant) future.

Maintaining two build systems is a bit of a pain, and at various points I've run into issues with getting autotools to play nicely. Since this project needs portability (including Windows), CMake is a much better fit for the job, and I've generally found it easier to maintain (though it still isn't perfect). This also fits nicely with LLVM's recent decision to deprecate autotools support and push forward with just CMake.

I've already switched my internal nightly tests to use CMake, and I've just updated the README to reflect this change (I'll update the Wiki soon).

If anyone has any issues with the CMake build system, do let me know.

**Comment by P-p-H-d** [comment]
Could you keep a configure script accepting standard options (--prefix, --with-llvm, --with-readline, ...) as a wrapper around CMake?
I personally found the CMake interface for configuring rather ugly.

**Comment by jrprice** [comment]
I'm a little apprehensive about adding a wrapper script that hides CMake behind an autotools compatible configure script. Aside from the extra maintenance effort, I imagine this would surprise some users; the Makefiles that CMake generates behave differently to those generated by automake (e.g. different Makefile rules).

Is there something specific about Oclgrind's CMake interface that you don't like, or is it the CMake workflow in general that you object to?

**Comment by P-p-H-d** [comment]
There is nothing about specific about Oclgrind's CMake interface that I don't like.
It is the CMake general interface for end user (not for the developer):
./configure --prefix=/opt/oclgrind 
is nicer than
cmake . -DCMAKE_INSTALL_PREFIX=/opt/oclgrind 
just like the output of "./configure --help" to the output of "cmake --help-variables"

**Comment by hughperkins** [comment]
@P-p-H-d Have you tried `ccmake`? with 2 c's?  If it doesnt work do:
```
sudo apt-get install cmake-curses-gui
```
... and retry

**Comment by P-p-H-d** [comment]
I have tried it and last time I used it, I found it even more confusing than using cmake from the command line (but I don't remember why).
