### ISSUE TITLE
oclgrind script does not forward SIGTERM

### ISSUE THREAD

**Issue by mpflanzer** [jrprice/Oclgrind#86]
I notices the the oclgrind wrapper script does not forward the SIGTERM command to the actual executable. For instance, trying to kill the oclgrind process in htop only results in the bash being killed but the actual executable continues to run. (Ctrl-C does kill both but I've read that it works slightly different than just sending SIGTERM.)
I added exec before the call to the actual executable in the oclgrind script which solves the problem (https://github.com/jrprice/Oclgrind/commit/5103ad991473abb6ef274d901ba5b8770f5019cb). The bash is replaced by the actual program and thus there is only one process which has to be killed.

Do you see any problems with that?

**Comment by jrprice** [comment]
Looks like a reasonable change to me - I'd be happy to take a PR for that.

**Comment by mpflanzer** [comment]
Good, I created pull request #88

**Comment by jrprice** [comment]
Thanks!
