### ISSUE TITLE
LLVM error when trying to run applications

### ISSUE THREAD

**Issue by SakalisC** [jrprice/Oclgrind#87]
Hello,

I am getting the following error message when trying to run any OpenCL application:

```
: CommandLine Error: Option 'import-instr-limit' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

I am using Oclgrind v15.5-324-g5103ad9 with llvm and clang 3.8

**Comment by jrprice** [comment]
Which operating system are you using, and which (if any) other OpenCL platforms do you have installed?

I have a feeling this sort of error can occur if multiple OpenCL platforms are installed and are using LLVM. Do you get this error early on on the application execution, such as when discovering OpenCL platforms?

**Comment by SakalisC** [comment]
I am using Ubuntu 14.04 (Linux 4.2.0) and I have 3 OpenCL platforms installed (AMD, Intel, and a custom one).

I am getting the error before my application even has time to do anything (ie I can't even do a simple printf at the beginning of `main`).

**Comment by jrprice** [comment]
OK, and are you using Oclgrind via the ICD loader or are you using `oclgrind ./application args...`?

> v15.5-324-g5103ad9

I can't see that hash in the git history - are you using the last release (May 2015) or the latest sources from master? If you built from source, do any of the tests pass (`make test` or `make check`)?

**Comment by SakalisC** [comment]
I am using the standalone application. The correct hash is caf06f9 (latest from master), the sources I am using are added in the project as a submodule, hence the wrong hash.

`make test` returns with all the tests passing.
```
100% tests passed, 0 tests failed out of 83
```

**Comment by SakalisC** [comment]
Update: It seems that one of the OpenCL implementations is to blame, as removing them from the OpenCL ICD vendors solves the issue. However, why would the other implementations affect oclgrind?

**Comment by jrprice** [comment]
There's some static initialisation code in the LLVM libraries, and if multiple versions of these libraries are loaded from the same application it can cause these kinds of problems. This *shouldn't* happen if you run your application using the `oclgrind` command, unless your application uses LLVM itself (or via some other libraries).

**Comment by SakalisC** [comment]
Since this doesn't seem to be an `oclgrind` problem I will close the issue. Thanks for the help and the info.

**Comment by SakalisC** [comment]
For future reference, and in case anyone else stumbles into the same issue, it seems that the problem lies with `ocl-icd`. I tried the latest version and the issue disappears. I am fairly certain that it's because of [this](https://bugzilla.redhat.com/show_bug.cgi?id=1219646) issue that has since been fixed.
