### ISSUE TITLE
Seg fault on a simple case

### ISSUE THREAD

**Issue by gkontsevich** [jrprice/Oclgrind#91]
Hi,

I'm in the process of getting familiar with OpenCL and debugging it, so sorry if this is simple problem. I'm also not sure if my issue is with oclgrind or the Debian repository where i got it from. 

At first I tried to run oclgrind (with -i) on the opencl kernel for the HOG Descriptor in OpenCV - however the debugger never got triggered. So I'm now simply trying to run a much simpler case to verify that oclgrind actually works and it's causing a segmentations fault.

```
$oclgrind ./matvec
/usr/bin/oclgrind: line 145:  4306 Segmentation fault      LD_LIBRARY_PATH=$LIBDIR:$LD_LIBRARY_PATH LD_PRELOAD=$LIBDIR/liboclgrind-rt.so "$@"
```

The example I'm running is straight from a textbook. It's a matrix vector multiply. It runs to completion without oclgrind.

```
$./matvec
Matrix-vector multiplication successful.
```

the 
matvec.cl is:

```

// OpenCL Kernel
__kernel void matvec_mult(__global float4* matrix,
                          __global float4* vector,
                          __global float* result) {
        int i = get_global_id(0);
        result[i] = dot(matrix[i], vector[0]);
}

```
and matvec.c (the host code) is:

```
int main() {
// THE OPENCL VARIABLE
        cl_platform_id platform;// a vendor's implementation of OpenCL
        cl_device_id device;    // the GPU/CPU etc.
        cl_context context;     // a container for the host to manage the devices
        cl_command_queue queue; // list of kernels to be executes by a device
        cl_int i, err;
        cl_program program;
        FILE *program_handle;
        char *program_buffer, *program_log;
        size_t program_size, log_size;
        cl_kernel kernel;       // OpenCL code that is combined with argument data and sent to a queue
        size_t work_units_per_kernel;
        float mat[16], vec[4], result[4];
        float correct[4] = {0.0f, 0.0f, 0.0f, 0.0f};
        cl_mem mat_buff, vec_buff, res_buff;

// INITIALIZE DATA
        for(i=0; i<16; i++) {
                mat[i] = i * 2.0f;
        }
        for(i=0; i<4;
            i++) {
                vec[i] = i
                        * 3.0f;
                correct[0]
                        += mat[i]
                        *
                        vec[i];
                correct[1]
                        += mat[i+4]
                        *
                        vec[i];
                correct[2]
                        += mat[i+8]
                        *
                        vec[i];
                correct[3]
                        += mat[i+12]
                        *
                        vec[i];
        }

// SET OPENCL VARIABLES
        clGetPlatformIDs(1, &platform, NULL); // set the platform
        clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1,
                       &device, NULL);        // set the device
        context = clCreateContext(NULL, 1, &device, NULL,
                                  NULL, &err);// set the context

// READ OPENCL PROGRAM FILE
        program_handle = fopen(PROGRAM_FILE, "r");
        fseek(program_handle, 0, SEEK_END);
        program_size = ftell(program_handle);
        rewind(program_handle);
        program_buffer = (char*)malloc(program_size + 1);
        program_buffer[program_size] = '\0';
        fread(program_buffer, sizeof(char), program_size,
              program_handle);
        fclose(program_handle);

// COMPILE OPENCL KERNEL
        program = clCreateProgramWithSource(context, 1,
                                            (const char**)&program_buffer, &program_size, &err);
        free(program_buffer);
        clBuildProgram(program, 0, NULL, NULL, NULL, NULL);

// CREATE KERNEL AND QUEUE
        kernel = clCreateKernel(program, KERNEL_FUNC, &err);
        queue = clCreateCommandQueue(context, device, 0, &err);

        mat_buff = clCreateBuffer(context, CL_MEM_READ_ONLY |
                                  CL_MEM_COPY_HOST_PTR, sizeof(float)*16, mat, &err);
        vec_buff = clCreateBuffer(context, CL_MEM_READ_ONLY |
                                  CL_MEM_COPY_HOST_PTR, sizeof(float)*4, vec, &err);
        res_buff = clCreateBuffer(context, CL_MEM_WRITE_ONLY,
                                  sizeof(float)*4, NULL, &err);

// SET KERNEL ARGUMENTS
        clSetKernelArg(kernel, 0, sizeof(cl_mem), &mat_buff);
        clSetKernelArg(kernel, 1, sizeof(cl_mem), &vec_buff);
        clSetKernelArg(kernel, 2, sizeof(cl_mem), &res_buff);

// EXECUTE KERNEL (ie. send to the command queue)
        work_units_per_kernel = 4;
        clEnqueueNDRangeKernel(queue, kernel, 1, NULL,
                               &work_units_per_kernel, NULL, 0, NULL, NULL);

// READ/PRINT RESULTS
        clEnqueueReadBuffer(queue, res_buff, CL_TRUE, 0,
                            sizeof(float)*4, result, 0, NULL, NULL);
        if((result[0] == correct[0]) && (result[1] == correct[1])
           && (result[2] == correct[2]) && (result[3] == correct[3]))
        {
                printf("Matrix-vector multiplication successful.\n");
        }
        else
        {
                printf("Matrix-vector multiplication unsuccessful.\n");
        }
        clReleaseMemObject(mat_buff);
        clReleaseMemObject(vec_buff);
        clReleaseMemObject(res_buff);
        clReleaseKernel(kernel);
        clReleaseCommandQueue(queue);
        clReleaseProgram(program);
        clReleaseContext(context);
        return 0;
}


```

Maybe it's something simple I'm doing wrong, or maybe it's a larger issue with the application.

Any help would be greatly appreciated
Thank you,

George

**Comment by jrprice** [comment]
If you're on a Debian system, could you `apt-get install clinfo` and then try running `oclgrind clinfo` to see if it's working at all?

This could well be a bug in Oclgrind, but without any sort of backtrace it's hard to say for sure. Could you also try `oclgrind gdb ./matvec` and see if you can get a backtrace from that? (if you're not familiar with GDB it should just be `run` and then `backtrace`).

**Comment by gkontsevich** [comment]
Thank you for getting back to me! Again, I really appreciate the help
Thanks for pointing out  `clinfo` - it's really handy. 
`oclgrind clinfo ` seems to work fine and detects the oclgrind simulator device. I don't see anything suspicious in the output.. but if you'd like I can paste it here too.

I'm getting the following backtrace through GDB

```
(gdb) run
Starting program: /home/gk/Programs/opencl-test/matvec_mult/matvec 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bce27e in clCreateKernel () from /usr/bin/../lib/oclgrind/liboclgrind-rt.so
(gdb) backtrace
#0  0x00007ffff7bce27e in clCreateKernel () from /usr/bin/../lib/oclgrind/liboclgrind-rt.so
#1  0x0000000000401042 in main ()
(gdb) 
```

the library is in the indicated location too

`-rw-r--r-- 1 root root 173296 Dec 16 09:33 /usr/lib/oclgrind/liboclgrind-rt.so `

for sanity checking I've tried running both as root and my normal user account

**Comment by jrprice** [comment]
The `matvec_mult` code you are using is specifically asking for a GPU device:

    clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1,
                              &device, NULL);        // set the device

Since Oclgrind reports itself as a CPU device, this will fail. The code you're using doesn't check for errors at any point, so will blindly continue with an uninitialised context, which is likely why you are getting a segmentation fault further down the line.

I realise that you got this code out of a textbook, but it is absolutely *crucial* to check the return codes of any OpenCL API functions that you call for this reason. See [my StackOverflow post here](http://stackoverflow.com/a/28477858/3100482) for details about how this can be done.

You should be able to fix this by just changing that call to use `CL_DEVICE_TYPE_ALL` instead.

**Comment by jrprice** [comment]
In the absence of manual error checking as I described above, you can use the `--check-api` feature of Oclgrind to automatically report API errors and information about their causes. For example, if I run the code you posted above with this feature, I get the following output:

    $ oclgrind --check-api ./matvec 

    Oclgrind - OpenCL runtime error detected
	    Function: clGetDeviceIDs
	    Error:    CL_DEVICE_NOT_FOUND


    Oclgrind - OpenCL runtime error detected
	    Function: clCreateContext
	    Error:    CL_INVALID_DEVICE


    Oclgrind - OpenCL runtime error detected
	    Function: clCreateProgramWithSource
	    Error:    CL_INVALID_CONTEXT
	    For argument 'context'


    Oclgrind - OpenCL runtime error detected
	    Function: clBuildProgram
	    Error:    CL_INVALID_PROGRAM
	    For argument 'program'

    [1]    25987 segmentation fault (core dumped)  oclgrind --check-api ./matvec

**Comment by gkontsevich** [comment]
I confirmed things on my end as well and you're exactly right.
So looks like opencl is working just fine! Sorry to have troubled you. I guess the issue with why the OpenCV kernels aren't triggering the oclgrind debugger is unrelated

I think the fact that I can run oclgrind around gdb is a really fantastic feature. It should help me narrow down what's going on. And I will definitely be adding error checks in the future

Thank you again Mr. Price. Couldn't have solved this without your help
