### ISSUE TITLE
build issue " CMake Error at /usr/share/llvm-3.6/cmake/LLVMConfig.cmake:52 (include):    include could not find load file:       /usr/lib/llvm-3.6/share/llvm/cmake/LLVMExports.cmake  Call Stack (most recent call first):    CMakeLists.txt:44 (find_package)"

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#95]
Doing any of the following gives the same error:
- on ubuntu 16.04, git clone the repo, apt-get install libclang-3.8-dev, libllvm-3.8-dev, run ccmake ..
- create a docker container with ubuntu 14.04, git clone the repo, apt-get install libclang-3.6-dev, libllvm-3.6-dev, run ccmake

I tried hacking around with the llvm LLVMConfig.cmake, and stuff, but seemed like going down a rabbit hole.  Presumably there's some simple way to solve this?

**Comment by jrprice** [comment]
This looks familiar, I remember dealing with this for the Debian LLVM 3.7 packages which had the CMake  configuration slightly wrong. I've reproduced this on an Ubuntu 16.04 VM, so I'll if I can produce a fix.

In the meantime, I've just tested this against the `3.7` versions of Clang and LLVM in the Ubuntu repositories and it builds fine. You'd need to pass `-DLLVM_DIR=/usr/share/llvm-3.7/cmake` to `cmake`. You'll also need `apt-get install clang-3.7 zlib1g-dev libedit-dev`.

In 16.04 you can also just `apt-get install oclgrind`, but the version you get is a little out-of-date (same as the last GitHub release).

Thanks for reporting.

**Comment by hughperkins** [comment]
> In 16.04 you can also just apt-get install oclgrind, but the version you get is a little out-of-date (same as the last GitHub release).

Ah, sounds good.  will try that.

**Comment by hughperkins** [comment]
Whoa, cool :-O 
```
Number of platforms                               1
  Platform Name                                   Oclgrind
  Platform Vendor                                 University of Bristol
  Platform Version                                OpenCL 1.2 (Oclgrind 15.5)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             oclg

  Platform Name                                   Oclgrind
Number of devices                                 1
  Device Name                                     Oclgrind Simulator
  Device Vendor                                   University of Bristol
  Device Vendor ID                                0x42
  Device Version                                  OpenCL 1.2 (Oclgrind 15.5)
  Driver Version                                  Oclgrind 15.5
  Device OpenCL C Version                         OpenCL C 1.2 (Oclgrind 15.5)
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               1
  Max clock frequency                             1MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             65536x65536x65536
  Max work group size                             65536
  Preferred work group size multiple              1
```

**Comment by hughperkins** [comment]
Hmmmm, given the bug about device ids, I have no choice but to build from source really. 

=> reopening

**Comment by hughperkins** [comment]
Here is what I get currently: ```
git/Oclgrind/build$ rm -Rf ~/git/Oclgrind/build/* ; cmake -DLLVM_DIR=/usr/share/llvm-3.7/cmake ..
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
LLVM_INSTALL_PREFIX /usr
CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:179 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  CMakeLists.txt:44 (find_package)


CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:182 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  CMakeLists.txt:44 (find_package)


-- Found LLVM 3.8.0
-- Using LLVMConfig.cmake in: /usr/share/llvm-3.8/cmake
CMake Error at CMakeLists.txt:60 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/git/Oclgrind/build/CMakeFiles/CMakeOutput.log".
```

**Comment by hughperkins** [comment]
Oooo, that gets past cmake now :-)  note that I needed also `libclang-3.7-dev`.

=> closing for now
