### ISSUE TITLE
on ubuntu 16.04, using the binary icd doesnt seem to work?

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#96]
on ubuntu 16.04, using the binary icd doesnt seem to work?

- downloaded  Oclgrind-15.5-Linux.tgz
- decompressed
- set following env vars:
```
PATH=$PATH:$HOME/Downloads/oclgrind-15.5/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/Downloads/oclgrind-15.5/lib
```
- created following icd:
```
/home/ubuntu/Downloads/oclgrind-15.5/lib/liboclgrind-rt-icd.so
```
- removed all other icd files (but note that `clinfo` etc works fine with my other icd files)
- run clinfo:
   - what I expect to happen: see information about the virtual oclgrind platform aand device
   - what realy happens: `Number of platforms                               0`

Thoughts?

**Comment by jrprice** [comment]
Thanks for reporting, reproduced on my own system. I tend to use the `oclgrind` command almost exclusively so don't really test the ICD path on Linux anymore. Can you verify that running `oclgrind clinfo` works (if `oclgrind-15.5/bin` is on your `PATH`)?

**Comment by hughperkins** [comment]
going with the `apt-get` solution for now => closing this for now :-)

**Comment by hughperkins** [comment]
But yes, if I remove the icd file, running `oclgrind clinfo` works :-)

**Comment by hughperkins** [comment]
(but nothing else works:
```
> oclgrind ./gpuinfo 
num platforms: 0
No platforms found => exiting
```)

**Comment by hughperkins** [comment]
(note that with apt-get, if I create my own icd file, like: ```
cat /etc/OpenCL/vendors/oclgrind.icd 
/usr/lib/oclgrind/liboclgrind-rt.so
```
...this works ok for me)

**Comment by hughperkins** [comment]
Reopening, after building from source, for which icd doesnt work

**Comment by hughperkins** [comment]
So:
- I set INSTALL_PREFIX to `$HOME/git/Oclgrind/dist`, and `make install`d into there
- my `LD_LIBRARY_PATH` is `/home/ubuntu/git/Oclgrind/dist/lib`
- `/home/ubuntu/git/Oclgrind/dist/bin/oclgrind clinfo` does work
- according to what I put in the icd file, different results for `clinfo`:
  - `/home/ubuntu/git/Oclgrind/dist/lib/liboclgrind-rt.so` => clinfo reports 1 platform, then hangs
  - `/home/ubuntu/git/Oclgrind/dist/lib/liboclgrind.so` => 0 platforms
  - `/home/ubuntu/git/Oclgrind/dist/lib/liboclgrind-rt-icd.so` => 0 platforms

**Comment by hughperkins** [comment]
Not priority for now, since can run via using `oclgrind`
=> closing
