### ISSUE TITLE
oclgrind claims to be a cpu.  would be nice to have an option to make it claim to be a gpu :-)

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#97]
oclgrind claims to be a cpu.  would be nice to have an option to make it claim to be a gpu :-)

For example, in cltorch, I dont allow people to run on cpus, since it wont work, since pretty much most/many things need at least ~32 threads per warp to work ok.  (edit: well: >=32 threads per workgroup to be fair)

**Comment by jrprice** [comment]
Fixed by 60e429b.

**Comment by hughperkins** [comment]
Cool.  Thank you :-)
